Refactor snapshot creation logic and enhance help documentation

diff --git a/btrfs-snapshot b/btrfs-snapshot
--- a/btrfs-snapshot
+++ b/btrfs-snapshot
@@ -12,115 +12,67 @@ function takeSnapshot () {
 
     shift
 
-    # Check if the script is running as root
-    test "$(id -u)" -eq "0" || { echo "Must be root to run this script"; exit 1; }
-
-    # Check if btrfs is the filesystem in use.
-    mount | grep "on / type btrfs" > /dev/null 2>&1 || { sysLog "Root filesystem is not btrfs"; exit 1; }
-
     while true ; do case "${1}" in
-        -y|--yes                ) forceSnapshot="yes" ;;
-        -r|--readonly           ) readOnly="yes"      ;;
-        *                   ) break ;;
+        -h|--help ) echo "${helpInfo}" ; cat help-create.txt ; exit 0 ;;
     esac ; shift ; done
-
-    # Check if the snapshot directory exists
-    test -d "${SNAPSHOT_DIR}" || { sysLog "Snapshot directory does not exist"; exit 1; }
-
-    if test "${readOnly}" = "yes" && test "${forceSnapshot}" = "no" ; then
-
-        read -rp "Are you sure you want to create a read-only snapshot? (y/N) " answer
-        case "${answer}" in
-            [yY]                ) readOnly="yes"       ;;
-            [nN]                ) readOnly="no"        ;;
-            ""                  ) readOnly="no"        ;;
-            *                   )
-                sysLog "failed to create snapshot: ${answer}"
-                echo "Invalid answer: ${answer}" ; exit 1
-            ;;
-        esac
-
-    fi
-
-    echo "Creating snapshot..." ; sleep 2
-
-    # Take a snapshot of the root filesystem
-    if test "${readOnly}" = "yes" ; then
-        btrfs su snapshot -r / "${SNAPSHOT_PATH}" > /dev/null 2>&1 || { sysLog "Failed to create snapshot" ; exit 1; }
-    else
-        btrfs su snapshot / "${SNAPSHOT_PATH}" > /dev/null 2>&1 || { sysLog "Failed to create snapshot" ; exit 1; }
-    fi
-
-    echo "Snapshot created: ${SNAPSHOT_PATH}" ; sleep 2
-
-    sysLog "Snapshot created: ${SNAPSHOT_PATH}"
 
 }
 
 set -eo pipefail
 
-# Set readOnly to "no" by default
-readOnly="no"
-forceSnapshot="no"
+# shellcheck disable=SC1091
+source /etc/btrfs-snapshot.conf || {
+    sysLog "Configuration file /etc/btrfs-snapshot.conf not found" ; exit 1
+}
 
+test ! -f /etc/os-release || source /etc/os-release
+
+_appName="btrfs-snapshot"
+_appVersion="$(cat /usr/share/doc/btrfs-snapshot/version || echo "unknown")"
+
+# Default values for general snapshot for the root filesystem
+_distroName="${DISTRO_NAME:-$NAME}"
+_snapshotType="${SNAPSHOT_TYPE:-root}"
+
+_snapshotDir="${SNAPSHOT_DIR:-/.snapshots}"
+_setDate="${SET_DATE:-true}"
+_readOnly="${READ_ONLY:-false}"
+
+_licenseInfo="$(cat << EOF
+$_appName - Copyright (c) 2024 by Michael L. Schaecher <MichaelLeeSchaecher@gmail.com> under the terms
+of the GPLv3 License or later.
+EOF
+)"
+
+# How many snapshots to keep. This should be keep low to avoid using too much disk space.
+_totalCount="${TOTAL_COUNT:-7}"
 versionInfo="$(cat << EOF
-btrfs-snapshot - [VERSION] $(cat /usr/share/doc/btrfs-snapshot/version || echo "unknown") - $(date +%Y-%m-%d)
+${_appName} [ version ${_appVersion} ] - ${_distroName}
 EOF
 )"
 
 helpInfo="$(cat << EOF
 ${versionInfo}
 
-Usage: btrfs-snapshot create [-r|--readonly <yes|no>] [-h|--help] [-v|--version]
-
-Commands:
-    create                        Create a snapshot of the root filesystem
-    help                          Show this help message
-    version                       Show version information
+Usage: ${_appName} [options] <flags> arg...
 
 Options:
-    -r, --readonly    <yes|no>    Create a read-only snapshot (default: no)
-                                  WARNING: Setting this may cause boot issues with some systems.
-                                           use at your own risk.
+    create                      Create a new snapshot based on configured settings: [use -h, --help for more options].
+    delete                      Delete a snapshot based on configured settings: [use -h, --help for more options].
+    restore                     Restore a subvolume to a previous state: [use -h, --help for more options].
+    list                        List all snapshots in the snapshot directory.
+    help                        Show this help message.
+    version                     Show version information.
 
-    -y, --yes                     Do not prompt for confirmation
-
-Description:
-    This script creates a snapshot of the root filesystem using btrfs and deletes old snapshots
-    to keep the total number of snapshots within a specified limit. The script must be run as root
-    and requires btrfs to be the filesystem in use.
-
-    The script uses the following environment variables:
-        - SNAPSHOT_DIR: Directory where snapshots are stored (default: /.snapshots)
-        - TOTAL_KEEP: Total number of snapshots to keep (default: 1O)
-        - SNAPSHOT_PATH: Path to the snapshot (default: /.snapshots/$(date +%Y-%m-%d_%H-%M-%S))
 
 EOF
 )"
 
-# shellcheck disable=SC1091
-if test -f /etc/btrfs-snapshot.conf ; then
-    source /etc/btrfs-snapshot.conf
-else
-    sysLog "Configuration file /etc/btrfs-snapshot.conf not found"
-    exit 1
-fi
-
-test ! -f /etc/os-release || source /etc/os-release
-
-_snapshotDir="${SNAPSHOT_DIR:-/.snapshots}"
-_distroName="{DISTRO_NAME:-${NAME}"
-_snapshotType="${SNAPSHOT_TYPE:-root}"
-_setDate="${SET_DATE:-true}"
-_readOnly="${READ_ONLY:-false}"
-_totalCount="${TOTAL_COUNT:-7}"
-
-
 case "${1}" in
-    create                  ) takeSnapshot "${@}"                   ;;
-    help                    ) echo "${helpInfo}" ; exit 0           ;;
-    version                 ) echo "${versionInfo}" ; exit 0        ;;
-    *                       ) echo "Invalid argument: ${1}"; exit 1 ;;
+    create                  ) takeSnapshot "${@}"                        ;;
+    help                    ) echo "${helpInfo}" ; cat help.txt ; exit 0 ;;
+    version                 ) echo "${versionInfo}" ; exit 0             ;;
+    *                       ) echo "Invalid argument: ${1}"; exit 1      ;;
 esac
 
 # Delete snapshots exceeding the total to keep
