Enhance reset_env function with additional cleanup and success/error messages

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,13 +6,21 @@ set -e
 function check_installed () { dpkg -s "$1" &>/dev/null ; }
 
 function reset_env () {
+
     rm -rv debian/.* debian/"$(basename "$(pwd)")" \
         debian/files \
         debian/{changelog,changelog.gz} 2>/dev/null \
         debian/*.substvars \
         debian/*.ex \
         debian/*.debhelper \
-        doc/man/"$(basename "$(pwd)")".{1,conf.5} || true
+        doc/man/"$(basename "$(pwd)")".{1,5,8} || true
+
+        if [ "$?" -eq 0 ] ; then
+            echo -e "\033[32mEnvironment reset successfully.\033[0m"
+        else
+            echo -e "\033[31mFailed to reset the environment.\033[0m"
+            exit 1
+        fi
 }
 
 function build_deb () {
